export const FETCH_TASKS_START = 'FETCH_TASKS_START';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const SET_TASKS_SUCCESS = 'SET_TASKS_SUCCESS';
export const SET_ACTION = 'SET_ACTION';
export const RESET_ACTION = 'RESET_ACTION';
export const SET_CURRENT_TASK = 'SET_CURRENT_TASK';
export const TOGGLE_DESCRIPTION = 'TOGGLE_DESCRIPTION';
